language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

install:
  - composer install --no-interaction

script:
  - vendor/bin/phpcs ./
  - XDEBUG_MODE=coverage php vendor/bin/codecept run --coverage-xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
